# Generated by Django 4.1.7 on 2023-03-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=5000)),
                ('short_description', models.TextField(max_length=255)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('release_date', models.DateTimeField()),
                ('genre', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
    ]
